namespace Deck.EncoderCheck;

/// <summary>
/// The icon the product ships with, read straight off disk.
/// <para>
/// This is a file that is generated by hand-run tooling and then committed, which is the shape of
/// thing that goes stale silently: change the mark, forget to regenerate, and the release carries the
/// old letter. Worse, an icon can be committed and never wired up at all - a missing
/// <c>ApplicationIcon</c> costs nothing at build time and ships an application wearing the default
/// WPF sheet of paper, which nobody notices until it is in a taskbar.
/// </para>
/// <para>
/// So this parses the container itself rather than asking Windows to open it. The generator writes the
/// bytes with its own code and checks them back through WPF's decoder; this reads them with a third
/// implementation, which is the only way for the check to be able to disagree.
/// </para>
/// </summary>
internal static class IconChecks
{
    /// <summary>The sizes Windows asks for. Nine of them, and all nine have to be there.</summary>
    private static readonly int[] Expected = [16, 20, 24, 32, 40, 48, 64, 128, 256];

    // The application icon carries its own ground: the petrol accent, with the mark in the light
    // theme's near-white. Stated here rather than imported, so that changing the palette in one place
    // and not the other is a failure rather than a surprise.
    private static readonly (byte R, byte G, byte B) Tile = (0x2A, 0x6A, 0x70);
    private static readonly (byte R, byte G, byte B) Mark = (0xF4, 0xF5, 0xF3);

    public static int Run()
    {
        var failures = 0;

        var root = RepositoryRoot();
        if (root is null)
        {
            Console.WriteLine("  FAIL could not find the repository root, so the icon was never checked");
            return 1;
        }

        var iconPath = Path.Combine(root, "src", "Deck.App", "Deck.ico");
        var projectPath = Path.Combine(root, "src", "Deck.App", "Deck.App.csproj");

        failures += Check("the icon is where the build expects it", () =>
        {
            Expect(File.Exists(iconPath), $"no icon at {iconPath}");
        });

        if (!File.Exists(iconPath)) return failures;

        var bytes = File.ReadAllBytes(iconPath);
        var entries = ReadDirectory(bytes);

        failures += Check("the executable is actually told to use it", () =>
        {
            // The one mistake that costs nothing to make and ships a default icon.
            var project = File.ReadAllText(projectPath);
            Expect(project.Contains("<ApplicationIcon>", StringComparison.Ordinal),
                "Deck.App.csproj has no ApplicationIcon, so the icon file is decoration");
            Expect(project.Contains("Deck.ico", StringComparison.Ordinal),
                "ApplicationIcon does not point at Deck.ico");
        });

        failures += Check("every size Windows asks for is present", () =>
        {
            var sizes = entries.Select(e => e.Width).Order().ToArray();

            Expect(sizes.SequenceEqual(Expected.Order()),
                $"sizes in the file are {string.Join(", ", sizes)}, expected {string.Join(", ", Expected)}");
        });

        failures += Check("each image is square, 32-bit, and declares itself honestly", () =>
        {
            foreach (var entry in entries)
            {
                Expect(entry.Width == entry.Height, $"{entry.Width}x{entry.Height} is not square");
                Expect(entry.BitCount == 32, $"the {entry.Width}px image is {entry.BitCount}-bit");

                // The directory says one thing and the bitmap header says another in plenty of icons
                // in the wild; the shell believes the header.
                Expect(entry.HeaderWidth == entry.Width,
                    $"the {entry.Width}px entry contains a {entry.HeaderWidth}px bitmap");

                // Doubled, because the format still reserves room for a 1-bit mask under the colours.
                Expect(entry.HeaderHeight == entry.Height * 2,
                    $"the {entry.Width}px bitmap declares height {entry.HeaderHeight}, expected {entry.Height * 2}");
            }
        });

        failures += Check("the letter still has a hole in it", () =>
        {
            // The counter is what makes the shape a D rather than a slab, and it is one fill rule away
            // from being filled in - both figures are wound the same way, so drawing it under the
            // nonzero rule instead of even-odd loses the counter and nothing warns about it.
            foreach (var entry in entries)
            {
                var cut = CutFor(entry.Width);
                var counter = Pixel(bytes, entry, cut.X + (cut.Width / 2), cut.Y + (cut.Height / 2));

                Expect(Same(counter, Tile),
                    $"the counter of the {entry.Width}px mark is #{counter.R:X2}{counter.G:X2}{counter.B:X2}, " +
                    "not the ground showing through");
            }
        });

        failures += Check("the mark is drawn in the mark colour", () =>
        {
            foreach (var entry in entries)
            {
                var cut = CutFor(entry.Width);
                var bar = Pixel(bytes, entry, cut.X + (cut.Width / 2), cut.Y + (cut.Thickness / 2));

                Expect(Same(bar, Mark),
                    $"the top bar of the {entry.Width}px mark is #{bar.R:X2}{bar.G:X2}{bar.B:X2}");
            }
        });

        failures += Check("every size is the exact drawing it is supposed to be", () =>
        {
            // The checks above ask whether the icon is shaped like a D. This one asks whether it is
            // *this* D, and it exists because the first version of this file did not: moving a cut by a
            // pixel and regenerating passed every one of them, because a probe in the middle of the
            // counter stays in the middle of the counter.
            //
            // Measured rather than sampled. The stem, the bars and the bowl are all axis-aligned, so
            // they land on whole pixels at every size and the bounding box of solid mark-coloured
            // pixels is the cut itself - only the chamfers are ever antialiased, and they only affect
            // the corners.
            foreach (var entry in entries)
            {
                var cut = CutFor(entry.Width);
                var bounds = MarkBounds(bytes, entry);

                Expect(bounds.MinX == cut.X && bounds.MinY == cut.Y,
                    $"the {entry.Width}px mark starts at {bounds.MinX},{bounds.MinY}, expected {cut.X},{cut.Y}");

                Expect(bounds.MaxX == cut.X + cut.Width - 1 && bounds.MaxY == cut.Y + cut.Height - 1,
                    $"the {entry.Width}px mark ends at {bounds.MaxX},{bounds.MaxY}, " +
                    $"expected {cut.X + cut.Width - 1},{cut.Y + cut.Height - 1}");

                // Across the middle of the counter: stem, hole, bowl. Measuring the stem pins the
                // weight, which is the one dimension a bounding box cannot see.
                var stem = RunLength(bytes, entry, cut.X, cut.Y + (cut.Height / 2));

                Expect(stem == cut.Thickness,
                    $"the {entry.Width}px stem is {stem} pixels wide, expected {cut.Thickness}");
            }
        });

        failures += Check("nothing touches the edge", () =>
        {
            foreach (var entry in entries)
            {
                var size = entry.Width;

                foreach (var (x, y, side) in new[]
                {
                    (size / 2, 0, "top"),
                    (size / 2, size - 1, "bottom"),
                    (0, size / 2, "left"),
                    (size - 1, size / 2, "right"),
                })
                {
                    var pixel = Pixel(bytes, entry, x, y);
                    Expect(Same(pixel, Tile), $"the {size}px mark reaches the {side} edge");
                }
            }
        });

        failures += Check("the icon is opaque all the way to its corners", () =>
        {
            // A tile with a soft edge looks like a mistake on a light taskbar and like a halo on a dark
            // one. Every pixel of an application icon that carries its own ground should be solid.
            foreach (var entry in entries)
            {
                foreach (var (x, y) in new[] { (0, 0), (entry.Width - 1, 0), (0, entry.Height - 1) })
                {
                    var pixel = Pixel(bytes, entry, x, y);
                    Expect(pixel.A == 255, $"the {entry.Width}px image has alpha {pixel.A} at {x},{y}");
                }
            }
        });

        return failures;
    }

    // ------------------------------------------------------------------ the container

    private readonly record struct Entry(
        int Width, int Height, int BitCount, int Offset, int HeaderWidth, int HeaderHeight);

    private static List<Entry> ReadDirectory(byte[] bytes)
    {
        var entries = new List<Entry>();

        var type = BitConverter.ToUInt16(bytes, 2);
        var count = BitConverter.ToUInt16(bytes, 4);

        if (type != 1) throw new Exception($"this is not an icon file - type {type}");

        for (var i = 0; i < count; i++)
        {
            var at = 6 + (i * 16);

            // Zero means 256: the field is one byte, so the largest size cannot be written literally.
            var width = bytes[at] == 0 ? 256 : bytes[at];
            var height = bytes[at + 1] == 0 ? 256 : bytes[at + 1];
            var bitCount = BitConverter.ToUInt16(bytes, at + 6);
            var offset = BitConverter.ToInt32(bytes, at + 12);

            entries.Add(new Entry(
                width, height, bitCount, offset,
                BitConverter.ToInt32(bytes, offset + 4),
                BitConverter.ToInt32(bytes, offset + 8)));
        }

        return entries;
    }

    /// <summary>
    /// One pixel out of an entry's bitmap. Rows run bottom-up and channels are BGRA, both of which are
    /// the opposite of what you would guess.
    /// </summary>
    private static (byte R, byte G, byte B, byte A) Pixel(byte[] bytes, Entry entry, int x, int y)
    {
        var pixels = entry.Offset + 40;
        var stride = entry.Width * 4;
        var row = entry.Height - 1 - y;
        var at = pixels + (row * stride) + (x * 4);

        return (bytes[at + 2], bytes[at + 1], bytes[at], bytes[at + 3]);
    }

    /// <summary>The bounding box of every solidly mark-coloured pixel in an image.</summary>
    private static (int MinX, int MinY, int MaxX, int MaxY) MarkBounds(byte[] bytes, Entry entry)
    {
        int minX = entry.Width, minY = entry.Height, maxX = -1, maxY = -1;

        for (var y = 0; y < entry.Height; y++)
        {
            for (var x = 0; x < entry.Width; x++)
            {
                if (!Same(Pixel(bytes, entry, x, y), Mark)) continue;

                if (x < minX) minX = x;
                if (y < minY) minY = y;
                if (x > maxX) maxX = x;
                if (y > maxY) maxY = y;
            }
        }

        if (maxX < 0) throw new Exception($"the {entry.Width}px image has no mark in it at all");

        return (minX, minY, maxX, maxY);
    }

    /// <summary>How many mark-coloured pixels run to the right from a starting point.</summary>
    private static int RunLength(byte[] bytes, Entry entry, int x, int y)
    {
        var run = 0;
        while (x + run < entry.Width && Same(Pixel(bytes, entry, x + run, y), Mark)) run++;
        return run;
    }

    // ------------------------------------------------------------------ the geometry

    /// <summary>
    /// The hinted cuts, repeated from <c>DeckMark</c> on purpose. Importing them would mean this check
    /// and the generator agreeing with each other by construction, which is not a check - the point is
    /// that changing the mark without regenerating the icon breaks something.
    /// </summary>
    private static (int X, int Y, int Width, int Height, int Thickness) CutFor(int size) => size switch
    {
        16 => (2, 2, 12, 12, 3),
        20 => (3, 2, 14, 16, 4),
        24 => (4, 3, 16, 18, 5),
        32 => (5, 4, 22, 24, 6),
        40 => (6, 5, 28, 30, 8),
        48 => (7, 6, 34, 36, 9),
        64 => (10, 8, 44, 48, 12),
        128 => (20, 16, 88, 96, 24),
        256 => (40, 32, 176, 192, 48),
        _ => throw new Exception($"no cut is recorded for {size}px"),
    };

    private static bool Same((byte R, byte G, byte B, byte A) pixel, (byte R, byte G, byte B) colour) =>
        Math.Abs(pixel.R - colour.R) <= 2 &&
        Math.Abs(pixel.G - colour.G) <= 2 &&
        Math.Abs(pixel.B - colour.B) <= 2;

    private static string? RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Deck.sln"))) return directory.FullName;
            directory = directory.Parent;
        }

        return null;
    }

    private static void Expect(bool condition, string message)
    {
        if (!condition) throw new Exception(message);
    }

    private static int Check(string name, Action action)
    {
        try
        {
            action();
            Console.WriteLine($"  ok   {name}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  FAIL {name}: {ex.Message}");
            return 1;
        }
    }
}
