using System.Text;
using Deck.Core;
using Deck.Core.Theming;

namespace Deck.EncoderCheck;

/// <summary>
/// The palette swatches on the website, generated from the product's own colours.
/// <para>
/// The site has always claimed its petrol is copied out of Theme.xaml rather than sampled by eye,
/// and that claim was kept by hand. Ten faces is too many to keep by hand: a palette adjusted in the
/// app would leave the page quietly showing the old one, which is worse than showing nothing, because
/// somebody choosing a palette from the page would be choosing something that no longer exists.
/// </para>
/// <para>
/// So this generates the block, <c>--site-palettes</c> prints it for pasting, and a check compares
/// what is in the page against what this produces. That makes the page's colours a copy that cannot
/// go stale rather than a promise that it has not.
/// </para>
/// </summary>
internal static class SitePalettes
{
    public const string Open = "/* ---- generated by Deck.EncoderCheck --site-palettes ---- */";

    public const string Close = "/* ---- end generated ---- */";

    /// <summary>Which product colour becomes which custom property on the page.</summary>
    private static readonly (string Property, string Key)[] Map =
    [
        ("ground", "BackgroundColor"),
        ("surface", "SurfaceColor"),
        ("line", "BorderColor"),
        ("text", "TextColor"),
        ("muted", "MutedTextColor"),
        ("accent", "AccentColor"),
        ("on-accent", "OnAccentColor"),
        ("live", "LiveColor"),
        ("mq", "MeterQuietColor"),
        ("mg", "MeterGoodColor"),
        ("ml", "MeterLoudColor"),
        ("mc", "MeterClipColor"),
        ("mq-off", "MeterQuietOffColor"),
        ("mg-off", "MeterGoodOffColor"),
        ("ml-off", "MeterLoudOffColor"),
        ("mc-off", "MeterClipOffColor"),
    ];

    public static string Css()
    {
        var css = new StringBuilder();
        css.Append(Open);

        foreach (var palette in Enum.GetValues<DeckPalette>())
        {
            foreach (var dark in new[] { false, true })
            {
                var colours = Palettes.Face(palette, dark).Colours();
                var face = dark ? "dark" : "light";
                var name = palette.ToString().ToLowerInvariant();

                css.Append($"\n  .palettes[data-face=\"{face}\"] [data-palette=\"{name}\"] {{");

                foreach (var (property, key) in Map)
                {
                    css.Append($" --p-{property}: {Web(colours[key])};");
                }

                css.Append(" }");
            }
        }

        css.Append('\n').Append(Close);
        return css.ToString();
    }

    /// <summary>ARGB as the app stores it, to the six-digit form the web wants. Every one is opaque.</summary>
    private static string Web(string argb)
    {
        var text = argb.TrimStart('#');

        return text.Length == 8
            ? "#" + text[2..]
            : "#" + text;
    }
}
